### ISSUE TITLE
Author/Forum link in Author Online Section redirect set up wrong

### ISSUE THREAD

**Issue by petersellars** [GitInPractice/Errata#1]
http://www.manning.com/GitinPractice
- link in Author online does not redirect to correct place...shouldn't it redirect here...

http://www.manning-sandbox.com/forum.jspa?forumID=895

**Comment by MikeMcQuaid** [comment]
It currently seems to redirect to https://forums.manning.com/forums/git-in-practice which seems to be correct. Sorry for the delay in replying; I realised when I created this repository I didn't remember to watch it. I appreciate the errata submission, thanks!
