### ISSUE TITLE
possible errata in descriptions of merge conflicts

### ISSUE THREAD

**Issue by jjwilley** [GitInPractice/Errata#2]
Since I'm still a Git novice, it's possible that the following is not an error in the text, but is instead simply my failure to understand the concepts fully. Having said that, it seems like the descriptions of merge conflics in Listings 2.11 and 5.7 may be in error.

My understanding is that the text should read:

Listing 2.11
-2 should read 'Current marker'
-3 should read 'Current line'
-5 should read 'Incoming marker'
-6 should read 'Incoming line'

Supporting text for Listing 2.11
-3 should read 'shows a line from the current branch'
-5 should read 'shows a line from the incoming branch'

If this is correct, similar changes would apply to Listing 5.7 and the supporting text.

**Comment by MikeMcQuaid** [comment]
Sorry for the delay in replying; I realised when I created this repository I didn't remember to watch it. I appreciate the errata submission, thanks!

**Comment by MikeMcQuaid** [comment]
And you're correct: well spotted.
