### ISSUE TITLE
Possible typo page 18 section 1.5

### ISSUE THREAD

**Issue by leepa** [GitInPractice/Errata#3]
The text reads:

```
This may seen surprising or worrying; after all, didn’t I just tell you
that the history contains the entire list of changes to the project over time?
```

`seen` should be `seem`?

**Comment by MikeMcQuaid** [comment]
Hey @leepa :wave:! Well spotted.

Sorry for the delay in replying; I realised when I created this repository I didn't remember to watch it. I appreciate the errata submission, thanks!
