### ISSUE TITLE
Chapter 6: Slight Error With Annotations in Listing 6.14

### ISSUE THREAD

**Issue by DiceBlackEnigma** [GitInPractice/Errata#7]
**Listing 6.14** which contains the output for **rewritten history push failure** has the annotations reversed. The annotation labelled `2 Local/remote branches` should actually be labelled `1 Local/remote branches` and the one labelled `1 push failure` should actually be labelled `2 push failure`. That way, they match the explanation given below the listing.

**Comment by MikeMcQuaid** [comment]
@DiceBlackEnigma Thanks for the report! Noted in the errata.
